version: '3'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=notifier
      - POSTGRES_USER=notifier
      - POSTGRES_PASSWORD=notifier
    volumes:
      - notifier_postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: notifier
      RABBITMQ_DEFAULT_PASS: notifier
      RABBITMQ_DEFAULT_VHOST: notifier
    volumes:
      - rabbitmq_volume:/var/lib/rabbitmq/mnesia

  web:
    build: .
    image: web:latest
    volumes:
      - .:/application
    ports:
      - 8000:8000
    depends_on:
      - db
      - rabbitmq
    environment:
      CELERY_BROKER: amqp://rabbitmq:rabbitmq@rabbitmq:5672/notifier

  workers:
    image: web:latest
    volumes:
      - .:/application
    command: celery -A notifier worker -l info
    depends_on:
      - db
      - rabbitmq
    environment:
      CELERY_BROKER: amqp://rabbitmq:rabbitmq@rabbitmq:5672/notifier

volumes:
  notifier_postgres:
  rabbitmq_volume:
