site_name: Notifier
nav:
  - Home: index.md
  - User guide:
    - Installation: user_guide/installation.md
    - Configuration: user_guide/configuration.md
    - How to write custom producer: user_guide/custom_producer_creation.md
    - How to write custom consumer: user_guide/custom_consumer_creation.md
    - How to write custom filter: user_guide/custom_filter_creation.md
  - Avaliable producers:
    - Github: producers/github.md
  - Avaliable consumers:
    - Telegram: consumers/telegram.md
  - Sources:
    - Configuration: sources/configuration.md
    - Helpers: sources/helpers.md
    - Message consumers: sources/message_consumers.md
    - Message producers: sources/message_producers.md
    - Message filters: sources/message_filters.md


theme:
  name: material
  palette:
    scheme: slate

markdown_extensions:
  - toc:
      permalink: "#"
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("notifier")
            - import os
            - import django
            - os.environ.setdefault("DJANGO_SETTINGS_MODULE", "notifier.settings")
            - django.setup()