# Generated by Django 3.1 on 2020-10-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_producers', '0002_auto_20201003_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='customproducer',
            name='executor',
            field=models.CharField(default='bash', max_length=100),
            preserve_default=False,
        ),
    ]
