# Generated by Django 3.1 on 2020-09-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_producers', '0005_auto_20200916_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomProducer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='custom_producers')),
            ],
        ),
    ]
