resources:
- db-statefulset.yaml
- db-service.yaml
- rabbitmq-statefulset.yaml
- rabbitmq-service.yaml
- web-deployment.yaml
- web-service.yaml
secretGenerator:
- name: sentry-token
  literals:
  - SENTRY_DSN=some_sentry_dsn

