resources:
- db-statefulset.yaml
- db-service.yaml
- rabbitmq-statefulset.yaml
- rabbitmq-service.yaml
- web-deployment.yaml
- web-service.yaml
secretGenerator:
- name: sentry-token
  files:
  - .sentry.txt
