apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  selector:
    matchLabels:
      app: rabbitmq
  serviceName: rabbitmq
  replicas: 1
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - name: queue-port
              containerPort: 5672
            - name: management-port
              containerPort: 15672
            - name: cluster-port
              containerPort: 4369
            - name: dist-port
              containerPort: 25672
          env:
            - name: RABBITMQ_DEFAULT_VHOST
              value: "notifier"
            - name: RABBITMQ_DEFAULT_USER
              value: "rabbitmq"
            - name: RABBITMQ_DEFAULT_PASS
              value: "rabbitmq"
