apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      service: web
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        service: web
    spec:
      initContainers:
        - name: wait-for-db
          image: hagassaan/notifier
          # TODO: make real check of db readiness
          command: ['sh', '-c', "sleep 10"]
        - name: run-migrations
          image: hagassaan/notifier
          command: ['sh', '-c', "./manage.py migrate"]
          env:
            - name: DB_PORT
              value: "5432"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-token
                  key: SENTRY_DSN
      containers:
        - name: web
          image: hagassaan/notifier
          ports:
          - containerPort: 8000
            protocol: TCP
          env:
            - name: DB_PORT
              value: "5432"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-token
                  key: SENTRY_DSN
        - name: workers
          image: hagassaan/notifier
          command: ["celery"]
          args: ["-A", "notifier", "worker", "-l", "INFO"]
          env:
            - name: DB_PORT
              value: "5432"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-token
                  key: SENTRY_DSN
        - name: beat
          image: hagassaan/notifier
          command: ["celery"]
          args: ["-A", "notifier", "beat", "-l", "INFO"]
          env:
            - name: DB_PORT
              value: "5432"
            - name: SENTRY_DSN
              valueFrom:
                secretKeyRef:
                  name: sentry-token
                  key: SENTRY_DSN
