apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      service: web
  replicas: 1
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
        - name: web
          image: hagassaan/notifier
          ports:
          - containerPort: 8000
            protocol: TCP
          env:
            - name: DB_PORT
              value: "5432"
        - name: workers
          image: hagassaan/notifier
          command: ["celery"]
          args: ["-A", "notifier", "worker", "-l", "INFO"]
          env:
            - name: DB_PORT
              value: "5432"
        - name: beat
          image: hagassaan/notifier
          command: ["celery"]
          args: ["-A", "notifier", "beat", "-l", "INFO"]
          env:
            - name: DB_PORT
              value: "5432"
