apiVersion: batch/v1
kind: Job
metadata:
  name: web
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - name: migration
        image: hagassaan/notifier
        command: ["python"]
        args: ["./manage.py", "migrate"]
        env:
        - name: DB_PORT
          value: "5432"
      restartPolicy: "Never"
