apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  selector:
    matchLabels:
      service: web
  replicas: 1
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
        - name: web
          image: hagassaan/notifier
          ports:
          - containerPort: 8000
            protocol: TCP
          env:
            - name: SENTRY_DSN
              value: "some_sentry_dsn_from_secret"
        - name: workers
          image: hagassaan/notifier
          command: ["celery"]
          args: ["-A", "notifier", "worker", "-l", "info"]
          env:
            - name: SENTRY_DSN
              value: "some_sentry_dsn_from_secret"
        # TODO: test it
        # TODO: wait for upgrade of lib, cuz now it conflicts with celery 5.*
        - name: beat
          image: hagassaan/notifier
          command: ["celery"]
          args: ["-A", "notifier", "beat", "-l", "info", "--scheduler", "django_celery_beat.schedulers:DatabaseScheduler"]
          env:
            - name: SENTRY_DSN
              value: "some_sentry_dsn_from_secret"
