apiVersion: batch/v1
kind: Job
metadata:
  name: web
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - name: migration
        image: hagassaan/notifier
        command: ["python"]
        args: ["./manage.py", "migrate"]
      restartPolicy: "Never"
