# Generated by Django 3.1 on 2020-09-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='configuration',
            name='message_filters',
            field=models.ManyToManyField(to='configuration.MessageFilter'),
        ),
    ]
