# Generated by Django 3.1.2 on 2020-11-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_consumers', '0004_auto_20201102_2136'),
        ('message_producers', '0004_auto_20201102_2136'),
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='consumer',
        ),
        migrations.RemoveField(
            model_name='configuration',
            name='producer',
        ),
        migrations.AddField(
            model_name='configuration',
            name='_consumers',
            field=models.ManyToManyField(blank=True, to='message_consumers.ConsumerModel'),
        ),
        migrations.AddField(
            model_name='configuration',
            name='_producers',
            field=models.ManyToManyField(blank=True, to='message_producers.ProducerModel'),
        ),
    ]
