# Generated by Django 3.1 on 2020-08-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='github_username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_username',
        ),
        migrations.AddField(
            model_name='user',
            name='additional_info',
            field=models.JSONField(default=None),
        ),
    ]
