# Generated by Django 3.1 on 2020-08-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20200814_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='additional_info',
            field=models.JSONField(default=None, null=True),
        ),
    ]
