# Generated by Django 3.1 on 2020-09-14 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_auto_20200914_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFilterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parameters', models.JSONField()),
                ('object_type', models.CharField(choices=[('SkipKeywordsMessageFilter', 'SkipKeywordsMessageFilter')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='MessageFilter',
        ),
        migrations.AlterField(
            model_name='configuration',
            name='message_filters',
            field=models.ManyToManyField(to='configuration.MessageFilterModel'),
        ),
    ]
