# Generated by Django 3.1 on 2020-09-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_auto_20200914_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefiltermodel',
            name='object_type',
            field=models.CharField(choices=[('SkipKeywordsMessageFilter', 'SkipKeywordsMessageFilter'), ('ReceiverExistsMessageFilter', 'ReceiverExistsMessageFilter'), ('ReceiverWorkingMessageFilter', 'ReceiverWorkingMessageFilter')], max_length=100),
        ),
        migrations.AlterField(
            model_name='messagefiltermodel',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
