# Generated by Django 3.1 on 2020-08-14 17:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_auto_20200814_1400'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='working_time_end',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='working_time_start',
            field=models.TimeField(default=datetime.datetime.now),
        ),
    ]
