# Generated by Django 3.1 on 2020-09-16 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_auto_20200914_1643'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='skip_keywords',
            new_name='_skip_keywords',
        ),
    ]
