# Generated by Django 3.1 on 2020-09-16 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_auto_20200916_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='message_filters',
            new_name='_message_filters',
        ),
    ]
