# Generated by Django 3.1 on 2020-09-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_auto_20200916_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuration',
            name='_skip_keywords',
        ),
    ]
