# Generated by Django 3.1 on 2020-10-02 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_remove_configuration__skip_keywords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SkipKeyword',
        ),
    ]
