# Generated by Django 3.1 on 2020-10-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0011_delete_skipkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='_message_filters',
            field=models.ManyToManyField(blank=True, to='configuration.MessageFilterModel'),
        ),
    ]
