# Generated by Django 3.1 on 2020-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0012_auto_20201002_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagefiltermodel',
            name='object_type',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
