# Generated by Django 3.1 on 2020-08-30 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_consumers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumermodel',
            name='object_type',
            field=models.CharField(choices=[('TelegramGroupChat', 'TelegramGroupChat'), ('TelegramChat', 'TelegramChat'), ('GoogleChat', 'GoogleChat')], max_length=100),
        ),
    ]
