# Generated by Django 3.1 on 2020-09-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_consumers', '0002_auto_20200830_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumermodel',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
