# Generated by Django 3.1 on 2020-09-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_consumers', '0003_auto_20200914_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumermodel',
            name='parameters',
            field=models.JSONField(blank=True, default=dict),
            preserve_default=False,
        ),
    ]
