# Generated by Django 3.1.2 on 2020-11-02 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_consumers', '0003_customconsumer_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customconsumer',
            name='executor',
            field=models.CharField(choices=[('python', 'Python'), ('bash', 'Bash')], default='bash', max_length=100),
        ),
    ]
