# Generated by Django 3.1 on 2020-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_consumers', '0006_auto_20200916_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumermodel',
            name='object_type',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
